version: '3.8'

services:
  api:
    image: matfire/spotitech
    environment:
      - DB_HOST=db
      - DB_PORT=3306
    ports:
      - "8000:3000"
    restart: "unless-stopped"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-net

  db:
    image: mysql:8.0
    user: root
    volumes:
      - ./my_spotify_db.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=spotify
      - MYSQL_USER=spoty
      - MYSQL_PASSWORD=spotypwd
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - app-net

networks:
  app-net:
    driver: bridge