 services:
  api:
    image: matfire/spotitech
    environment:
      - DB_HOST=db
      - DB_PORT=3306
    ports:
      - "8000:3000"
    restart: "unless-stopped"
    depends_on:
      - db
    entrypoint: ["./wait-for-it.sh", "db:3306", "--", "npm", "run", "start"]
  db:
    image: mysql
    volumes:
      - ./my_spotify_db.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./data/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=spotify
      - MYSQL_USER=spoty
      - MYSQL_PASSWORD=spotypwd
